### PR TITLE
Update go pkgs with gorepoman

### PR DESCRIPTION
**Pull request by butanian**
--- Update go packages with gorepoman ---
789e0fc gorepoman update github.com/BurntSushi/toml
32d48c3 gorepoman update github.com/aws/aws-sdk-go
9bc79a8 gorepoman update github.com/fullstorydev/gorepoman
975ffd0 gorepoman update github.com/golang/protobuf
6b27251 gorepoman update github.com/googleapis/gax-go
c1b94d6 gorepoman update github.com/lib/pq
1677af6 gorepoman update github.com/pkg/errors
f9f23ed gorepoman update golang.org/x/net
6e8d933 gorepoman update golang.org/x/oauth2
dcdd12d gorepoman update golang.org/x/text
15d6d93 gorepoman update google.golang.org/genproto
10f4b1c gorepoman update google.golang.org/grpc
e7357f2 gorepoman reconcile cloud.google.com/go
fcea667 gorepoman reconcile google.golang.org/api

--- Changes to fix compilation errors after package updates ---
32bc7a5 Use new bigquery.TableMetadata when creating tables in bigquery

### CODE REVIEW

**Comment by butanian** [comment]
@jameremo PTAL. The gorepoman crusade continues!

Had to update bigquery table creation code to match the latest bq library. To test I just ran main.go locally. Any other test ideas?

**Comment by butanian** [comment]
Definitely first tried gorepoman update for all the packages and only did reconcile after it complained. The reconcile was able to deal with the update gracefully.  I didn't have to merge anything manually, so didn't investigate further.

**Comment by jameremo** [comment]
For posterity: the reconcile issue was caused by a series of `.DS_Store` directories that we had erroneously committed to the repo. These were causing the content hash to be off, which in turn made `gorepoman` think that we had some custom changes committed to the tree, and thus a reconcile was necessary.

@butanian  Let's go ahead and remove those folders, and then I think this is ready to merge.

**Comment by butanian** [comment]
@jameremo got rid of the .DS_Store files and confirmed the packages (cloud.google.com/go, google.golang.org/api) work with just update.

**Comment by jameremo** [comment]
I still find 4 `.DS_Store` folders when I check out the branch. Could you double-check these?
```
find . -name ".DS_Store"
./vendor/cloud.google.com/.DS_Store
./vendor/golang.org/x/oauth2/.DS_Store
./vendor/github.com/golang/.DS_Store
./vendor/github.com/googleapis/.DS_Store
```

**Comment by butanian** [comment]
those .DS_Store files didn't interfere with updates, but removed anyway. Also more updates since I first uploaded the PR!

**Pull request merged**
